theme: theme
title: Thoughts
author: Jason Morley
email: support@jbmorley.co.uk
description: Lightweight Note Taking for macOS
baseurl: ""
url: https://thoughts.jbmorley.co.uk
repository: https://github.com/inseven/thoughts
copyright: 2024-2025 <a href="https://jbmorley.co.uk/about">Jason Morley</a>

navigation:
  - title: Thoughts
    href: /
  - title: Releases
    href: /releases
  - title: GitHub
    href: https://github.com/inseven/thoughts
  - title: Donate
    href: https://jbmorley.co.uk/support/

footer:
  - title: Privacy Policy
    href: /privacy-policy
  - title: Support
    href: /support
  - title: License
    href: /license
  - title: More Software
    href: https://jbmorley.co.uk/software/

plugins:
  - jekyll-feed
  - jekyll-environment-variables
  - jekyll-toc
destination: ../_site

defaults:
  - values:
      layout: "page"
