title: Thoughts
email: support@jbmorley.co.uk
description: ""
baseurl: ""
url: "https://thoughts.jbmorley.co.uk"

# Build settings
theme: minima
plugins:
  - jekyll-feed
destination: ../_site

defaults:
  - values:
      layout: "default"
