title: Thoughts
author: Jason Morley
email: support@jbmorley.co.uk
description: Lightweight Note Taking for macOS
baseurl: ""
url: "https://thoughts.jbmorley.co.uk"

plugins:
  - jekyll-feed
  - jekyll-environment-variables
  - jekyll-toc
destination: ../_site

defaults:
  - values:
      layout: "default"
